#!/usr/bin/env python3
"""Create a deterministic, read-only inventory of a software repository.

The scanner reads filesystem metadata only. It never opens project files, so
secret values, source contents, and environment-variable values are not emitted.
Inventory signals describe repository shape; they are not architecture verdicts.
"""

from __future__ import annotations

import argparse
import heapq
import json
import os
import re
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable, Optional


SCHEMA_VERSION = 1
MAX_REPORTED_PATHS = 100
MAX_REPORTED_ERRORS = 100
DEFAULT_MAX_DEPTH = 8
DEFAULT_MAX_FILES = 50_000
DEFAULT_MAX_DIRECTORIES = 20_000
DEFAULT_MAX_ENTRIES_PER_DIRECTORY = 10_000
DEFAULT_MAX_FILE_SIZE = 5 * 1024 * 1024

IGNORED_DIRS = {
    ".git", ".hg", ".svn", ".idea", ".vscode", "node_modules",
    "bower_components", "vendor", "__pycache__", ".pytest_cache",
    ".mypy_cache", ".ruff_cache", ".tox", ".nox", ".venv", "venv",
    "env", "dist", "build", "out", "target", "coverage", ".next",
    ".nuxt", ".turbo", ".cache", ".parcel-cache", ".gradle", ".expo",
    "pods", "deriveddata", "bin", "obj",
}
SENSITIVE_DIRS = {".ssh", ".aws", ".azure", ".gcloud", "credentials", "secrets", "private"}
SENSITIVE_NAME_RE = re.compile(
    r"^(?:\.env(?:\..*)?|\.npmrc|\.netrc|credentials?(?:\..*)?|"
    r"secrets?(?:\..*)?|.*(?:\.pem|\.p12|\.pfx|\.key)|"
    r"id_(?:rsa|dsa|ecdsa|ed25519)(?:\.pub)?)$",
    re.IGNORECASE,
)

LANGUAGES: dict[str, tuple[str, ...]] = {
    "JavaScript": (".js", ".cjs", ".mjs", ".jsx"),
    "TypeScript": (".ts", ".cts", ".mts", ".tsx"),
    "Python": (".py", ".pyi"),
    "C#": (".cs", ".csx"),
    "Java": (".java",),
    "Kotlin": (".kt", ".kts"),
    "Go": (".go",),
    "Rust": (".rs",),
    "Ruby": (".rb",),
    "PHP": (".php",),
    "C/C++": (".c", ".h", ".cc", ".cpp", ".hpp"),
    "Swift": (".swift",),
    "Dart": (".dart",),
    "HTML": (".html", ".htm"),
    "CSS": (".css", ".scss", ".sass", ".less"),
    "SQL": (".sql",),
    "Shell": (".sh", ".bash", ".zsh"),
    "PowerShell": (".ps1", ".psm1", ".psd1"),
    "Markdown": (".md", ".mdx"),
    "YAML": (".yaml", ".yml"),
    "JSON": (".json",),
    "XML": (".xml",),
    "Dockerfile": (".dockerfile",),
}
EXTENSION_LANGUAGE = {
    extension: language
    for language, extensions in LANGUAGES.items()
    for extension in extensions
}

MANIFEST_NAMES = {
    "package.json", "pyproject.toml", "setup.py", "setup.cfg", "cargo.toml",
    "go.mod", "pom.xml", "build.gradle", "build.gradle.kts", "gemfile",
    "composer.json", "pubspec.yaml", "mix.exs", "deno.json", "deno.jsonc",
    "makefile", "justfile", "project.clj", "build.sbt", "*.csproj", "*.sln",
}
LOCK_NAMES = {
    "package-lock.json", "npm-shrinkwrap.json", "pnpm-lock.yaml", "yarn.lock",
    "bun.lock", "bun.lockb", "poetry.lock", "uv.lock", "pipfile.lock",
    "pdm.lock", "cargo.lock", "composer.lock", "gemfile.lock", "go.sum",
    "mix.lock", "pubspec.lock", "gradle.lockfile",
}
ENTRYPOINT_NAMES = {
    "main.py", "app.py", "manage.py", "main.js", "main.ts", "index.js",
    "index.ts", "server.js", "server.ts", "app.js", "app.ts", "program.cs",
    "main.go", "main.rs", "main.dart", "main.swift", "application.java",
    "application.kt", "wsgi.py", "asgi.py", "dockerfile",
}
CI_MARKERS = {".github/workflows", ".circleci", ".buildkite", ".husky"}
CI_FILES = {".gitlab-ci.yml", "azure-pipelines.yml", "jenkinsfile", "bitbucket-pipelines.yml"}
INFRA_DIRS = {"infra", "infrastructure", "terraform", "k8s", "kubernetes", "helm", "charts"}
TEST_DIRS = {"test", "tests", "spec", "specs", "__tests__", "e2e", "integration"}
GENERATED_DIRS = {
    "generated", "gen", "codegen", "autogenerated", "auto-generated", "migrations_generated",
}
WORKSPACE_MARKERS = {
    "pnpm-workspace.yaml", "lerna.json", "nx.json", "turbo.json", "rush.json",
    "pnpm-workspace.yml", "melos.yaml", "workspace.json",
}


def _is_sensitive(name: str) -> bool:
    return bool(SENSITIVE_NAME_RE.match(name))


def _ignored_path(relative: str, name: str, is_dir: bool, user_ignores: set[str]) -> bool:
    folded_name = name.casefold()
    folded_relative = relative.casefold()
    if _is_sensitive(name):
        return True
    if is_dir and folded_name in SENSITIVE_DIRS:
        return True
    if is_dir and folded_name in IGNORED_DIRS:
        return True
    for ignored in user_ignores:
        folded_ignored = ignored.casefold().strip("/\\")
        if not folded_ignored:
            continue
        if "/" in folded_ignored or "\\" in folded_ignored:
            normalized = folded_ignored.replace("\\", "/")
            if folded_relative == normalized or folded_relative.startswith(normalized + "/"):
                return True
        elif folded_name == folded_ignored:
            return True
    return False


def _git_evidence(root: Path) -> dict[str, Any]:
    result: dict[str, Any] = {
        "available": False,
        "root": None,
        "branch": None,
        "commit": None,
        "dirty": None,
    }
    try:
        top = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"], cwd=root, text=True,
            capture_output=True, timeout=3, check=True,
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return result

    result["available"] = True
    git_root = Path(top).resolve()
    try:
        result["root"] = git_root.relative_to(root.resolve()).as_posix() or "."
    except ValueError:
        result["root"] = "ancestor"

    commands = {
        "branch": ["git", "symbolic-ref", "--quiet", "--short", "HEAD"],
        "commit": ["git", "rev-parse", "--short=12", "HEAD"],
    }
    for key, command in commands.items():
        try:
            value = subprocess.run(
                command, cwd=root, text=True, capture_output=True, timeout=3, check=True,
            ).stdout.strip()
            result[key] = value or None
        except (OSError, subprocess.SubprocessError):
            result[key] = None

    try:
        status = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=normal"],
            cwd=root, text=True, capture_output=True, timeout=5, check=True,
        ).stdout
        result["dirty"] = bool(status.strip())
    except (OSError, subprocess.SubprocessError):
        result["dirty"] = None
    return result


def _entry_categories(relative: str, name: str, is_dir: bool) -> set[str]:
    path = relative.casefold()
    basename = name.casefold()
    parts = path.split("/")
    categories: set[str] = set()

    if is_dir:
        if basename in INFRA_DIRS or basename in {".circleci", ".github"}:
            categories.add("directories")
        return categories

    if basename in MANIFEST_NAMES or basename.endswith((".csproj", ".sln")):
        categories.add("manifests")
    if basename in LOCK_NAMES:
        categories.add("lockfiles")
    if basename in ENTRYPOINT_NAMES:
        categories.add("entrypoints")
    if basename in WORKSPACE_MARKERS:
        categories.add("workspaces")
    if basename in CI_FILES or any(
        marker in path for marker in CI_MARKERS
    ):
        categories.add("ci_cd")
    if basename in {"dockerfile", "compose.yaml", "compose.yml", "docker-compose.yml", "docker-compose.yaml"}:
        categories.add("infrastructure")
    if Path(name).suffix.casefold() == ".tf" or any(part in INFRA_DIRS for part in parts[:-1]):
        categories.add("infrastructure")
    if any(part in TEST_DIRS for part in parts[:-1]) or basename.endswith(("_test.py", ".test.js", ".test.ts", ".spec.js", ".spec.ts")):
        categories.add("tests")
    if "adr" in parts or "decisions" in parts or basename.startswith("adr-"):
        categories.add("adrs")
    if Path(name).suffix.casefold() in {".md", ".mdx", ".rst", ".adoc"} or "docs" in parts:
        categories.add("documentation")
    return categories


def inventory(
    root: Path,
    *,
    max_depth: int = DEFAULT_MAX_DEPTH,
    max_files: int = DEFAULT_MAX_FILES,
    max_directories: int = DEFAULT_MAX_DIRECTORIES,
    max_entries_per_directory: int = DEFAULT_MAX_ENTRIES_PER_DIRECTORY,
    max_file_size: int = DEFAULT_MAX_FILE_SIZE,
    ignores: Iterable[str] = (),
) -> dict[str, Any]:
    """Inventory a repository without reading any file contents."""
    root = root.expanduser().resolve()
    if not root.is_dir():
        raise ValueError(f"repository path is not a directory: {root}")
    if max_depth < 0 or max_files < 1 or max_directories < 1 or max_entries_per_directory < 1 or max_file_size < 0:
        raise ValueError("scan limits must be non-negative; max-files, max-directories, and max-entries-per-directory must be at least 1")

    user_ignores = {value.strip() for value in ignores if value.strip()}
    directories: list[str] = []
    top_level: list[dict[str, str]] = []
    file_paths: list[str] = []
    category_paths: dict[str, list[str]] = defaultdict(list)
    language_files: Counter[tuple[str, str]] = Counter()
    language_bytes: Counter[tuple[str, str]] = Counter()
    directory_files: Counter[str] = Counter()
    directory_bytes: Counter[str] = Counter()
    large_files: list[dict[str, Any]] = []
    generated_areas: set[str] = set()
    ignored_counts: Counter[str] = Counter()
    errors: list[dict[str, str]] = []
    truncation_reasons: list[str] = []
    scanned_bytes = 0
    scanned_file_count = 0
    scanned_directory_count = 0
    reached_file_limit = False

    def record_error(relative: str, error: OSError) -> None:
        if len(errors) < MAX_REPORTED_ERRORS:
            errors.append({"path": relative or ".", "error": error.__class__.__name__})

    stack: list[tuple[Path, str, int]] = [(root, ".", 0)]
    while stack and not reached_file_limit:
        if scanned_directory_count >= max_directories:
            truncation_reasons.append(f"max-directories:{max_directories}")
            break
        directory, relative_directory, depth = stack.pop()
        scanned_directory_count += 1
        try:
            with os.scandir(directory) as iterator:
                entries = heapq.nsmallest(
                    max_entries_per_directory + 1,
                    iterator,
                    key=lambda item: (item.name.casefold(), item.name),
                )
            if len(entries) > max_entries_per_directory:
                entries = entries[:max_entries_per_directory]
                truncation_reasons.append(
                    f"max-entries-per-directory:{relative_directory}:{max_entries_per_directory}"
                )
        except OSError as error:
            record_error(relative_directory, error)
            continue

        child_directories: list[tuple[Path, str, int]] = []
        for entry in entries:
            relative = entry.name if relative_directory == "." else f"{relative_directory}/{entry.name}"
            try:
                is_dir = entry.is_dir(follow_symlinks=False)
                is_file = entry.is_file(follow_symlinks=False)
            except OSError as error:
                record_error(relative, error)
                continue

            if _ignored_path(relative, entry.name, is_dir, user_ignores):
                if _is_sensitive(entry.name) or (is_dir and entry.name.casefold() in SENSITIVE_DIRS):
                    ignored_counts["sensitive"] += 1
                else:
                    ignored_counts["configured_or_generated"] += 1
                continue

            if is_dir:
                directories.append(relative)
                if "/" not in relative:
                    top_level.append({"path": relative, "kind": "directory"})
                if entry.name.casefold() in GENERATED_DIRS:
                    generated_areas.add(relative)
                if depth >= max_depth:
                    truncation_reasons.append(f"max-depth:{max_depth}")
                    continue
                child_directories.append((Path(entry.path), relative, depth + 1))
                continue
            if not is_file:
                # Do not follow symbolic links, sockets, pipes, or device files.
                ignored_counts["non_regular"] += 1
                continue
            if scanned_file_count >= max_files:
                reached_file_limit = True
                truncation_reasons.append(f"max-files:{max_files}")
                break

            try:
                stat = entry.stat(follow_symlinks=False)
            except OSError as error:
                record_error(relative, error)
                continue

            size = stat.st_size
            scanned_file_count += 1
            scanned_bytes += size
            file_paths.append(relative)
            suffix = Path(entry.name).suffix.casefold() or "[no extension]"
            language = EXTENSION_LANGUAGE.get(suffix, "Other")
            language_files[(language, suffix)] += 1
            language_bytes[(language, suffix)] += size

            current_directory = relative_directory
            while current_directory != ".":
                directory_files[current_directory] += 1
                directory_bytes[current_directory] += size
                parent = current_directory.rpartition("/")[0]
                current_directory = parent or "."

            if size > max_file_size:
                if len(large_files) < MAX_REPORTED_PATHS:
                    large_files.append({"path": relative, "bytes": size, "reason": "file-size-limit"})
            for category in _entry_categories(relative, entry.name, False):
                if len(category_paths[category]) < MAX_REPORTED_PATHS:
                    category_paths[category].append(relative)
            if "/" not in relative:
                top_level.append({"path": relative, "kind": "file"})

        # Reverse push preserves ascending traversal with a LIFO stack.
        stack.extend(reversed(child_directories))

    for relative in directories:
        if relative.casefold().split("/")[-1] in GENERATED_DIRS:
            generated_areas.add(relative)

    large_directories = [
        {"path": path, "files": count, "bytes": directory_bytes[path]}
        for path, count in sorted(directory_files.items())
        if count >= 100 or directory_bytes[path] >= 10 * 1024 * 1024
    ]

    languages = [
        {
            "language": language,
            "extension": extension,
            "files": count,
            "bytes": language_bytes[(language, extension)],
        }
        for (language, extension), count in sorted(
            language_files.items(), key=lambda item: (-item[1], item[0][0].casefold(), item[0][1])
        )
    ]
    for values in category_paths.values():
        values.sort(key=lambda value: (value.casefold(), value))
    directories.sort(key=lambda value: (value.casefold(), value))
    top_level.sort(key=lambda item: (item["path"].casefold(), item["path"]))
    large_files.sort(key=lambda item: (-item["bytes"], item["path"].casefold(), item["path"]))
    large_directories.sort(key=lambda item: (-item["bytes"], item["path"].casefold()))
    errors.sort(key=lambda item: (item["path"].casefold(), item["error"]))
    truncation_reasons = sorted(set(truncation_reasons))
    partial = bool(errors or truncation_reasons)

    return {
        "schema_version": SCHEMA_VERSION,
        "root": str(root),
        "status": "partial" if partial else "complete",
        "summary": {
            "files": scanned_file_count,
            "directories": scanned_directory_count,
            "bytes": scanned_bytes,
        },
        "limits": {
            "max_depth": max_depth,
            "max_files": max_files,
            "max_directories": max_directories,
            "max_entries_per_directory": max_entries_per_directory,
            "large_file_detail_threshold_bytes": max_file_size,
            "file_contents_read": 0,
        },
        "scan": {
            "ignored": dict(sorted(ignored_counts.items())),
            "exclusions": {
                "default_ignored_directory_names": sorted(IGNORED_DIRS),
                "sensitive_paths_redacted": True,
                "custom_ignore_pattern_count": len(user_ignores),
                "symbolic_links_followed": False,
            },
            "truncation_reasons": truncation_reasons,
            "errors": errors,
        },
        "top_level": top_level[:MAX_REPORTED_PATHS],
        "directories": directories[:MAX_REPORTED_PATHS],
        "languages": languages[:50],
        "notable_files": {
            "manifests": category_paths["manifests"],
            "lockfiles": category_paths["lockfiles"],
            "workspaces": category_paths["workspaces"],
            "likely_entrypoints": category_paths["entrypoints"],
            "ci_cd": category_paths["ci_cd"],
            "tests": category_paths["tests"],
            "infrastructure": category_paths["infrastructure"],
            "documentation": category_paths["documentation"],
            "adrs": category_paths["adrs"],
        },
        "generated_or_large": {
            "generated_areas": sorted(generated_areas, key=lambda value: (value.casefold(), value))[:MAX_REPORTED_PATHS],
            "large_files": large_files,
            "large_directories": large_directories[:MAX_REPORTED_PATHS],
        },
        "git": _git_evidence(root),
        "interpretation": "Inventory signals are observations only; do not infer architecture quality from counts or names.",
    }


def _markdown(report: dict[str, Any]) -> str:
    summary = report["summary"]
    lines = [
        "# Repository inventory",
        "",
        f"- Root: `{report['root']}`",
        f"- Scan: **{report['status']}** — {summary['files']} files, {summary['directories']} directories, {summary['bytes']} bytes",
        f"- Git: {'available' if report['git']['available'] else 'not detected'}",
        f"- File contents read: {report['limits']['file_contents_read']}",
        f"- Bounds: depth {report['limits']['max_depth']}, {report['limits']['max_files']} files, {report['limits']['max_directories']} directories, {report['limits']['max_entries_per_directory']} entries/directory, large-file detail threshold {report['limits']['large_file_detail_threshold_bytes']} bytes",
        f"- Exclusions: {sum(report['scan']['ignored'].values())} paths/names omitted; sensitive names redacted; {report['scan']['exclusions']['custom_ignore_pattern_count']} extra ignore pattern(s); symlinks not followed",
        "",
        "> This is a bounded structural inventory, not an architecture assessment. Inspect relevant files and behavior before drawing conclusions.",
        "",
        "## Top-level structure",
        "",
    ]
    for entry in report["top_level"]:
        suffix = "/" if entry["kind"] == "directory" else ""
        lines.append(f"- `{entry['path']}{suffix}`")
    if not report["top_level"]:
        lines.append("- (empty)")

    lines.extend(["", "## Languages and file types", "", "| Language | Extension | Files | Bytes |", "|---|---:|---:|---:|"])
    for item in report["languages"]:
        lines.append(f"| {item['language']} | `{item['extension']}` | {item['files']} | {item['bytes']} |")
    if not report["languages"]:
        lines.append("| (none) | — | 0 | 0 |")

    labels = {
        "manifests": "Manifests", "lockfiles": "Lockfiles", "workspaces": "Workspace markers",
        "likely_entrypoints": "Likely entrypoints", "ci_cd": "CI/CD", "tests": "Tests",
        "infrastructure": "Infrastructure", "documentation": "Documentation", "adrs": "ADRs",
    }
    lines.extend(["", "## Navigation signals", ""])
    for key, label in labels.items():
        values = report["notable_files"][key]
        if values:
            rendered = ", ".join(f"`{path}`" for path in values[:12])
            if len(values) > 12:
                rendered += f", … (+{len(values) - 12} not listed)"
        else:
            rendered = "(none detected)"
        lines.append(f"- **{label}:** {rendered}")

    lines.extend(["", "## Large or generated areas", ""])
    generated = report["generated_or_large"]["generated_areas"]
    large_dirs = report["generated_or_large"]["large_directories"]
    large_files = report["generated_or_large"]["large_files"]
    lines.append(f"- Generated-name directories: {', '.join(f'`{path}`' for path in generated) if generated else '(none detected)'}")
    lines.append("- Large directories: " + (
        ", ".join(f"`{item['path']}` ({item['files']} files, {item['bytes']} bytes)" for item in large_dirs[:10])
        if large_dirs else "(none detected)"
    ))
    lines.append("- Files above detail threshold: " + (
        ", ".join(f"`{item['path']}` ({item['bytes']} bytes)" for item in large_files[:10])
        if large_files else "(none detected)"
    ))
    if report["scan"]["truncation_reasons"] or report["scan"]["errors"]:
        lines.extend(["", "## Partial scan", ""])
        for reason in report["scan"]["truncation_reasons"]:
            lines.append(f"- Limit reached: `{reason}`")
        for error in report["scan"]["errors"]:
            lines.append(f"- Could not inspect `{error['path']}` ({error['error']}).")
    git = report["git"]
    if git["available"]:
        lines.extend(["", "## Git evidence", "", f"- Branch: `{git['branch'] or 'unknown'}`", f"- Commit: `{git['commit'] or 'unknown'}`", f"- Working tree: {'dirty' if git['dirty'] else 'clean' if git['dirty'] is False else 'unknown'}"])
    lines.append("")
    return "\n".join(lines)


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", nargs="?", type=Path, default=Path.cwd(), help="repository root (default: current directory)")
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--max-depth", type=int, default=DEFAULT_MAX_DEPTH)
    parser.add_argument("--max-files", type=int, default=DEFAULT_MAX_FILES)
    parser.add_argument("--max-directories", type=int, default=DEFAULT_MAX_DIRECTORIES)
    parser.add_argument("--max-entries-per-directory", type=int, default=DEFAULT_MAX_ENTRIES_PER_DIRECTORY)
    parser.add_argument("--max-file-size", type=int, default=DEFAULT_MAX_FILE_SIZE, help="threshold for large-file details; file contents are never read")
    parser.add_argument("--ignore", action="append", default=[], metavar="PATH_OR_NAME", help="additional path or directory name to omit; repeatable")
    args = parser.parse_args(argv)
    try:
        report = inventory(
            args.path,
            max_depth=args.max_depth,
            max_files=args.max_files,
            max_directories=args.max_directories,
            max_entries_per_directory=args.max_entries_per_directory,
            max_file_size=args.max_file_size,
            ignores=args.ignore,
        )
    except (OSError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2
    if args.format == "json":
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        sys.stdout.write(_markdown(report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
